/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BloodReturn.java
 *
 * Created on Sep 7, 2014, 6:20:33 PM
 */
package gui.Anu;

import idgenerator.IDGenerator;
import controller.anu.BloodPacketDA;
import controller.anu.ReturnedLogController;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.ReturnedLog;

/**
 *
 * @author Anuradha
 */
public class BloodReturn extends javax.swing.JInternalFrame {

    ResultSet rst1 = null;
    ResultSet rst2 = null;

    /**
     * Creates new form BloodReturn
     */
    public BloodReturn() {

        initComponents();
        initPacketIDCombo();
        initSearchPacketIDCombo();

    }

    private void initPacketIDCombo() {
        packetIDCombo.removeAllItems();
        try {
            rst1 = BloodPacketDA.getAllBloodPackets();
            while (rst1.next()) {
                packetIDCombo.addItem(rst1.getString("packetID"));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BloodReturn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BloodReturn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initSearchPacketIDCombo() {
        searchPacketIDCombo.removeAllItems();
        try {
            rst2 = BloodPacketDA.getReturnedBloodPackets();
            while (rst2.next()) {
                searchPacketIDCombo.addItem(rst2.getString("packetID"));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BloodReturn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BloodReturn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        packetIDCombo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        bloodGroupTxt = new javax.swing.JTextField();
        markAsReturnedBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        bloodTypeTxt = new javax.swing.JTextField();
        returnedDateCalendar = new com.toedter.calendar.JCalendar();
        jLabel6 = new javax.swing.JLabel();
        reasonTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        bloodGroupTxt1 = new javax.swing.JTextField();
        bloodGroupTxt2 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        searchPacketIDCombo = new javax.swing.JComboBox();
        editBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        searchBloodGroupTxt = new javax.swing.JTextField();
        updateRecordBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        searchBloodTypeTxt = new javax.swing.JTextField();
        searchReturnedDateCalendar = new com.toedter.calendar.JCalendar();
        jLabel10 = new javax.swing.JLabel();
        searchReasonTxt = new javax.swing.JTextField();
        unmarkReturnBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        recievedQtyText2 = new javax.swing.JTextField();
        searchIssueIDTxt = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();

        jTabbedPane3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mark returned packet"));

        jLabel1.setText("Packet ID");

        jLabel3.setText("Issue ID");

        packetIDCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packetIDComboActionPerformed(evt);
            }
        });

        jLabel4.setText("Blood Group");

        bloodGroupTxt.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        bloodGroupTxt.setEnabled(false);
        bloodGroupTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupTxtActionPerformed(evt);
            }
        });

        markAsReturnedBtn.setText("Mark as returned");
        markAsReturnedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAsReturnedBtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Blood Type");

        bloodTypeTxt.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        bloodTypeTxt.setEnabled(false);
        bloodTypeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodTypeTxtActionPerformed(evt);
            }
        });

        returnedDateCalendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                returnedDateCalendarPropertyChange(evt);
            }
        });

        jLabel6.setText("Reason");

        reasonTxt.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        reasonTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reasonTxtActionPerformed(evt);
            }
        });

        jLabel12.setText("Issued Date");

        bloodGroupTxt1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        bloodGroupTxt1.setEnabled(false);
        bloodGroupTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupTxt1ActionPerformed(evt);
            }
        });

        bloodGroupTxt2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        bloodGroupTxt2.setEnabled(false);
        bloodGroupTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGroupTxt2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                                .addGap(4, 4, 4)))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bloodGroupTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 65, Short.MAX_VALUE))
                            .addComponent(reasonTxt)
                            .addComponent(bloodTypeTxt)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(packetIDCombo, 0, 134, Short.MAX_VALUE)
                            .addComponent(bloodGroupTxt1)
                            .addComponent(bloodGroupTxt2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(markAsReturnedBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnedDateCalendar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(returnedDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(markAsReturnedBtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(packetIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodGroupTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodGroupTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bloodGroupTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reasonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12))
        );

        jLabel51.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel51.setText("Add Returned Packet");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127))
        );

        jTabbedPane3.addTab("Returned Packets", jPanel11);

        jLabel11.setText("Packet ID");

        searchPacketIDCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPacketIDComboActionPerformed(evt);
            }
        });
        searchPacketIDCombo.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                searchPacketIDComboPropertyChange(evt);
            }
        });

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Packet Details"));

        jLabel7.setText("Issue ID");

        jLabel8.setText("Blood Group");

        searchBloodGroupTxt.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        searchBloodGroupTxt.setEnabled(false);
        searchBloodGroupTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBloodGroupTxtActionPerformed(evt);
            }
        });

        updateRecordBtn.setText("Update Record");
        updateRecordBtn.setEnabled(false);
        updateRecordBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRecordBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Blood Type");

        searchBloodTypeTxt.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        searchBloodTypeTxt.setEnabled(false);
        searchBloodTypeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBloodTypeTxtActionPerformed(evt);
            }
        });

        searchReturnedDateCalendar.setForeground(new java.awt.Color(255, 0, 0));
        searchReturnedDateCalendar.setEnabled(false);
        searchReturnedDateCalendar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                searchReturnedDateCalendarPropertyChange(evt);
            }
        });

        jLabel10.setText("Reason");

        searchReasonTxt.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        searchReasonTxt.setEnabled(false);
        searchReasonTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchReasonTxtActionPerformed(evt);
            }
        });

        unmarkReturnBtn.setText("Unmark Return");
        unmarkReturnBtn.setEnabled(false);
        unmarkReturnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unmarkReturnBtnActionPerformed(evt);
            }
        });

        jLabel13.setText("Issued Date");

        recievedQtyText2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        recievedQtyText2.setEnabled(false);
        recievedQtyText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recievedQtyText2ActionPerformed(evt);
            }
        });

        searchIssueIDTxt.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        searchIssueIDTxt.setEnabled(false);
        searchIssueIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchIssueIDTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(219, 219, 219))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(recievedQtyText2)
                                    .addComponent(searchBloodGroupTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchReasonTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(searchIssueIDTxt)
                                    .addComponent(searchBloodTypeTxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(searchReturnedDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(updateRecordBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unmarkReturnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchIssueIDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recievedQtyText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchBloodGroupTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchBloodTypeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(searchReasonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(searchReturnedDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unmarkReturnBtn)
                            .addComponent(updateRecordBtn))
                        .addGap(12, 12, 12))))
        );

        jLabel52.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel52.setText("Search/Update Blood Packet");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(searchPacketIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel52, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(searchPacketIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Search/Update Returned Blood Packet", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void packetIDComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packetIDComboActionPerformed

        ResultSet rst;
        try {
            rst = BloodPacketDA.getPacketDetails("" + packetIDCombo.getSelectedItem());
            while (rst.next()) {
                bloodGroupTxt.setText(rst.getString("bloodGroup"));
                bloodTypeTxt.setText(rst.getString("bloodType"));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BloodReturn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BloodReturn.class.getName()).log(Level.SEVERE, null, ex);
        }


}//GEN-LAST:event_packetIDComboActionPerformed

    private void bloodGroupTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupTxtActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_bloodGroupTxtActionPerformed

    private void markAsReturnedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markAsReturnedBtnActionPerformed

        String returnID = "";
        ResultSet rst;
        try {
            rst = ReturnedLogController.getResultIDs();
            rst.last();
            String curID = null;
            try {
                curID = rst.getString("returnedID");
                try {
                    returnID = IDGenerator.generateNextID(curID);
                } catch (Exception ex) {
                    Logger.getLogger(BloodReturn.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException e) {
                returnID = "R00001";
            }
            java.util.Date returnedDate = returnedDateCalendar.getDate();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String dateReturned = df.format(returnedDate);
            java.sql.Date sqlRetunedDate = new java.sql.Date(returnedDate.getTime());

            String packetID = "" + packetIDCombo.getSelectedItem();
            String reason = reasonTxt.getText();

            ReturnedLog log = new ReturnedLog(returnID, sqlRetunedDate, packetID, reason);

            int res1 = 0;
            int res2 = 0;

            res1 = ReturnedLogController.addReturnedLog(log);
            res2 = BloodPacketDA.markReturnedPacket(packetID);

            if ((res1 + res2) == 2) {
                JOptionPane.showMessageDialog(null, "Added Succesfully");
                initSearchPacketIDCombo();
            } else {
                JOptionPane.showMessageDialog(null, "Error!");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BloodReturn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BloodReturn.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_markAsReturnedBtnActionPerformed

    private void bloodTypeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodTypeTxtActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_bloodTypeTxtActionPerformed

    private void returnedDateCalendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_returnedDateCalendarPropertyChange
        //setRecievedTableItems();
}//GEN-LAST:event_returnedDateCalendarPropertyChange

    private void reasonTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reasonTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reasonTxtActionPerformed

    private void searchPacketIDComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPacketIDComboActionPerformed
        ResultSet rstBloodPacket;
        ResultSet rstReturnedLog;
        String packetID = "" + searchPacketIDCombo.getSelectedItem();
        try {
            rstBloodPacket = BloodPacketDA.getPacketDetails(packetID);
            rstReturnedLog = ReturnedLogController.getReturnedLog(packetID);
            //rstReturnedLog.last();
            while (rstBloodPacket.next()) {
                searchBloodGroupTxt.setText(rstBloodPacket.getString("bloodGroup"));
                searchBloodTypeTxt.setText(rstBloodPacket.getString("bloodType"));
            }
            if (rstReturnedLog.last() == true) {
                searchReasonTxt.setText(rstReturnedLog.getString("Reason"));
                java.sql.Date sqlDate = rstReturnedLog.getDate("ReturnedDate");
                java.util.Date utilDate = new java.util.Date(sqlDate.getTime());
                searchReturnedDateCalendar.setDate(utilDate);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BloodReturn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BloodReturn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchPacketIDComboActionPerformed

    private void searchBloodGroupTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBloodGroupTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBloodGroupTxtActionPerformed

    private void updateRecordBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRecordBtnActionPerformed
        String packetID = ""+searchPacketIDCombo.getSelectedItem();
        String returnID = "";
 
        ResultSet rst;
        try {
            rst = ReturnedLogController.getReturnedLog(packetID);
            if(rst.last() == true){
                System.out.println("Came");
                returnID = rst.getString("returnedID");
            }
            System.out.println("Return ID "+returnID);
            
            java.util.Date returnedDate = searchReturnedDateCalendar.getDate();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String dateReturned = df.format(returnedDate);
            java.sql.Date sqlRetunedDate = new java.sql.Date(returnedDate.getTime());

            String reason = searchReasonTxt.getText();

            ReturnedLog log = new ReturnedLog(returnID, sqlRetunedDate, packetID, reason);

            int res1 = 0;

            res1 = ReturnedLogController.updateReturnedLog(log);

            if (res1 == 1) {
                JOptionPane.showMessageDialog(null, "Updated Succesfully");
                searchReasonTxt.setEnabled(false);
                searchReturnedDateCalendar.setEnabled(false);
                updateRecordBtn.setEnabled(false);
                unmarkReturnBtn.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(null, "Error!");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BloodReturn.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BloodReturn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateRecordBtnActionPerformed

    private void searchBloodTypeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBloodTypeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchBloodTypeTxtActionPerformed

    private void searchReturnedDateCalendarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_searchReturnedDateCalendarPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_searchReturnedDateCalendarPropertyChange

    private void searchReasonTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchReasonTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchReasonTxtActionPerformed

    private void unmarkReturnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unmarkReturnBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unmarkReturnBtnActionPerformed

    private void bloodGroupTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroupTxt1ActionPerformed

    private void bloodGroupTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGroupTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGroupTxt2ActionPerformed

    private void recievedQtyText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recievedQtyText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_recievedQtyText2ActionPerformed

    private void searchIssueIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchIssueIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchIssueIDTxtActionPerformed

    private void searchPacketIDComboPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_searchPacketIDComboPropertyChange

    }//GEN-LAST:event_searchPacketIDComboPropertyChange

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        searchReasonTxt.setEnabled(true);
        searchReturnedDateCalendar.setEnabled(true);
        updateRecordBtn.setEnabled(true);
        unmarkReturnBtn.setEnabled(true);
    }//GEN-LAST:event_editBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bloodGroupTxt;
    private javax.swing.JTextField bloodGroupTxt1;
    private javax.swing.JTextField bloodGroupTxt2;
    private javax.swing.JTextField bloodTypeTxt;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JButton markAsReturnedBtn;
    private javax.swing.JComboBox packetIDCombo;
    private javax.swing.JTextField reasonTxt;
    private javax.swing.JTextField recievedQtyText2;
    private com.toedter.calendar.JCalendar returnedDateCalendar;
    private javax.swing.JTextField searchBloodGroupTxt;
    private javax.swing.JTextField searchBloodTypeTxt;
    private javax.swing.JTextField searchIssueIDTxt;
    private javax.swing.JComboBox searchPacketIDCombo;
    private javax.swing.JTextField searchReasonTxt;
    private com.toedter.calendar.JCalendar searchReturnedDateCalendar;
    private javax.swing.JButton unmarkReturnBtn;
    private javax.swing.JButton updateRecordBtn;
    // End of variables declaration//GEN-END:variables

}
