/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BloodRecieval.java
 *
 * Created on Sep 4, 2014, 9:57:34 PM
 */
package gui.Anu;

import controller.anu.EmployeeController;
import controller.anu.RecievedLogController;
import controller.anu.RequesteeDA;
import controller.anu.TestController;
import idgenerator.IDGenerator;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;
import model.Employee;

/**
 *
 * @author Anuradha
 */
public class BloodRecieval extends javax.swing.JInternalFrame {

    Nurse nurseForm = null;

    String[] title = {"Unit No", "Donor's Name", "Blood Group", "Blood Type", "Date of collection", "Date of Expiry", "TTI Results", "Remarks"};
    DefaultTableModel dtm = new DefaultTableModel(title, 0);

    /**
     * Creates new form BloodRecieval
     */
    public BloodRecieval(Nurse nurseForm) {
        initComponents();
        this.nurseForm = nurseForm;

        Calendar currenttime = Calendar.getInstance();
        java.util.Date today = new java.util.Date((currenttime.getTime()).getTime());
        recievedDateCalendar.setDate(today);

        setRequesteeCombo(requesteeCombo);
        setEmpCombo(empNamesCombo);

    }

    //recievalForm.setData(packetID,name,bloodGroup,bloodType,sqlDateC,sqlDateE,testResults,comment);
    public void setData(String packetID, String name, String bloodGroup, String bloodType, String dateC, String dateE, String testResults, String comment) {
        String[] row = {packetID, name, bloodGroup, bloodType, dateC, dateE, testResults, comment};
        dtm.addRow(row);
    }

    public JComboBox getRequesteeCombo() {
        return this.requesteeCombo;
    }

    public void setRequesteeCombo(JComboBox combo) {
        try {
            combo.removeAllItems();
            ResultSet rst = null;
            rst = RequesteeDA.getAllRequestees();

            while (rst.next()) {
                combo.addItem(rst.getString("RequesteeName"));
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BloodPacketForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BloodPacketForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setEmpCombo(JComboBox combo) {
        try {
            combo.removeAllItems();
            ResultSet rst = null;
            rst = EmployeeController.getAllEmployees();

            while (rst.next()) {
                combo.addItem(rst.getString("Name"));
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BloodPacketForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BloodPacketForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tempText = new javax.swing.JTextField();
        recievedDateCalendar = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        icePacketsCombo = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        empNamesCombo = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        AddPacketBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editPacketBtn = new javax.swing.JButton();
        addRecievalBtn = new javax.swing.JButton();
        deletePacketBtn = new javax.swing.JButton();
        requesteeCombo = new javax.swing.JComboBox();
        addSenderBtn = new javax.swing.JButton();
        recievedTimer = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jLabel8 = new javax.swing.JLabel();
        sendingOfficerText = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();

        jTabbedPane3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jPanel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 0, 204), new java.awt.Color(153, 255, 255), new java.awt.Color(0, 102, 255)));

        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Blood Recieval"));

        jLabel3.setText("Recieved Date");

        jLabel4.setText("Recieved Time");

        jLabel5.setText("Sent From");

        jLabel6.setText("Temperature inside the container at the time of recieval");

        tempText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempTextActionPerformed(evt);
            }
        });

        recievedDateCalendar.setDateFormatString("yyyy-MM-dd");

        jLabel11.setText("Ice Packets");

        icePacketsCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Frozen", "Dissolved", "Not found" }));

        jLabel12.setText("C");

        jLabel7.setText("Recieving Officer");

        empNamesCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Emp Names" }));

        AddPacketBtn.setText("Add Blood Packet");
        AddPacketBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddPacketBtnActionPerformed(evt);
            }
        });

        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 255, 255), new java.awt.Color(0, 0, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(0, 102, 255)));
        jTable1.setModel(dtm);
        jScrollPane1.setViewportView(jTable1);

        editPacketBtn.setText("Edit Blood Packet");

        addRecievalBtn.setText("Add Blood Recieval");
        addRecievalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRecievalBtnActionPerformed(evt);
            }
        });

        deletePacketBtn.setText("Delete Blood Packet");

        requesteeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Requestee Names" }));

        addSenderBtn.setText("Add new sender");
        addSenderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSenderBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Sending Officer");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(icePacketsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addComponent(tempText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(AddPacketBtn)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(deletePacketBtn)
                                .addGap(18, 18, 18)
                                .addComponent(editPacketBtn)
                                .addGap(18, 18, 18)
                                .addComponent(addRecievalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel19Layout.createSequentialGroup()
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel19Layout.createSequentialGroup()
                                        .addComponent(requesteeCombo, 0, 214, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)
                                        .addComponent(addSenderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(421, 421, 421))
                                    .addGroup(jPanel19Layout.createSequentialGroup()
                                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(recievedTimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(recievedDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sendingOfficerText, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(empNamesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requesteeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addSenderBtn))
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(icePacketsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3))
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(recievedDateCalendar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recievedTimer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tempText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sendingOfficerText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(empNamesCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddPacketBtn)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editPacketBtn)
                    .addComponent(addRecievalBtn)
                    .addComponent(deletePacketBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel51.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel51.setText("Add Blood Recieval");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(353, 353, 353))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Blood Recieval", jPanel11);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tempTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempTextActionPerformed

    private void AddPacketBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddPacketBtnActionPerformed
        RecievedBloodPacket bloodPacket = new RecievedBloodPacket(this);
        bloodPacket.setClosable(true);
        bloodPacket.setMaximizable(false);
        nurseForm.getDesktop().add(bloodPacket);
        nurseForm.getDesktop().setRequestFocusEnabled(true);
        bloodPacket.show();
    }//GEN-LAST:event_AddPacketBtnActionPerformed

    private void addSenderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSenderBtnActionPerformed
        AddRequestee requesteeForm = new AddRequestee(this);
        requesteeForm.setClosable(true);
        nurseForm.getDesktop().add(requesteeForm);
        nurseForm.getDesktop().setRequestFocusEnabled(true);
        requesteeForm.show();
    }//GEN-LAST:event_addSenderBtnActionPerformed

    private void addRecievalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRecievalBtnActionPerformed

        try {

            //===============================================================================================
            String recievedID = "";
            ResultSet rst;
            rst = RecievedLogController.getResultIDs();
            rst.last();
            String curID = null;
            try {
                curID = rst.getString("returnedID");
                try {
                    recievedID = IDGenerator.generateNextID(curID);
                } catch (Exception ex) {
                    Logger.getLogger(BloodReturn.class.getName()).log(Level.SEVERE, null, ex);
                }
            } catch (SQLException e) {
                recievedID = "RE00000001";
            }

            String requestee = "" + requesteeCombo.getSelectedItem();

            /*Recieved date*/
            java.util.Date dateR = recievedDateCalendar.getDate();
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            String dateRecieved = df.format(dateR);
            java.sql.Date sqlDateC = new java.sql.Date(dateR.getTime());

            /*Time*/
            SimpleDateFormat formatter = new SimpleDateFormat("hh:mm:ss");
            java.sql.Time sqlTime;
            try {
                sqlTime = new java.sql.Time(formatter.parse(recievedTimer.getFormatedTime()).getTime());
            } catch (ParseException ex) {
                Logger.getLogger(BloodRecieval.class.getName()).log(Level.SEVERE, null, ex);
            }

            String sendingOfficer = sendingOfficerText.getText();
            float temp = Float.parseFloat(tempText.getText());
            String icePacketCondition = "" + icePacketsCombo.getSelectedItem();
            String recievingOfficerID = EmployeeController.getEmpID(sendingOfficerText.getText());

        //=============================================================================================== BloodRecivedLog
            for (int i = 0; i < dtm.getRowCount(); i++) {
                String packetID = "" + dtm.getValueAt(i, 0);
        //================================================================================== BloodRecivedDetail
                //{packetID, name, bloodGroup, bloodType, dateC, dateE, testResults, comment};

                String donorName = "" + dtm.getValueAt(i, 1);   //Have to generate a (-) nic
                
                String bloodGroup = "" + dtm.getValueAt(i, 2);
                String bloodType = "" + dtm.getValueAt(i, 3);

                //Collection date
                SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
                Date parsed=null;
                try {
                    parsed = format.parse(""+dtm.getValueAt(i, 4));
                } catch (ParseException ex) {
                    Logger.getLogger(BloodRecieval.class.getName()).log(Level.SEVERE, null, ex);
                }
                java.sql.Date sqlDateCollection = new java.sql.Date(parsed.getTime());
                
                //Expiry date
                try {
                    parsed = format.parse(""+dtm.getValueAt(i, 5));
                } catch (ParseException ex) {
                    Logger.getLogger(BloodRecieval.class.getName()).log(Level.SEVERE, null, ex);
                }
                java.sql.Date sqlDateExpiry = new java.sql.Date(parsed.getTime());
                
                String ttiResults = ""+dtm.getValueAt(i, 6);;
                String comment = ""+dtm.getValueAt(i, 7);
                
                String[] tests = ttiResults.split(" ");   //Tests want to update test result table also
                
                                
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BloodRecieval.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(BloodRecieval.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_addRecievalBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddPacketBtn;
    private javax.swing.JButton addRecievalBtn;
    private javax.swing.JButton addSenderBtn;
    private javax.swing.JButton deletePacketBtn;
    private javax.swing.JButton editPacketBtn;
    private javax.swing.JComboBox empNamesCombo;
    private javax.swing.JComboBox icePacketsCombo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser recievedDateCalendar;
    private lu.tudor.santec.jtimechooser.JTimeChooser recievedTimer;
    private javax.swing.JComboBox requesteeCombo;
    private javax.swing.JTextField sendingOfficerText;
    private javax.swing.JTextField tempText;
    // End of variables declaration//GEN-END:variables

}
